BOOKS['07']={total:12,title:'Resources & Economic Geography',kicker:'Book 07 · Location and livelihood',dek:'Resource distribution, agriculture, minerals, energy, industries and transport.',prev:'06-physical-geography-of-india.html',next:'08-human-and-settlement-geography.html',sections:[
{id:'resources',title:'Resource concepts and distribution',html:`<p>A resource is created by interaction between nature, technology, demand and institutions. Reserves are economically recoverable under defined conditions; resources are broader. Renewable does not mean inexhaustible if extraction exceeds regeneration.</p><p>Distribution reflects geology, climate, ecology and history, while access reflects infrastructure, rights, capital and geopolitics. Resource abundance can support development or produce conflict, rent seeking and dependency if institutions are weak.</p>`},
{id:'minerals',title:'Minerals and energy',html:`<p>Metallic minerals often follow shields, fold belts and igneous processes; fossil fuels follow sedimentary basins; industrial minerals have varied settings. Ore grade, depth, energy, water, technology, transport and regulation determine viability.</p><p>Coal, petroleum and gas are dense but finite and polluting. Solar and wind are renewable but variable and land/grid intensive; hydropower is dispatchable/storage-capable but alters rivers and settlements; nuclear is low-carbon and firm but capital, safety and waste intensive. Energy geography is a system of resource, grid, storage, demand and justice.</p>`},
{id:'agriculture',title:'World and Indian agricultural patterns',html:`<p>Cropping reflects temperature, moisture, soil, relief, farm size, labour, market, technology and policy. Subsistence/intensive, commercial grain, plantation, mixed farming, dairy and pastoral systems occupy characteristic regions but evolve.</p><p>In India, monsoon, irrigation, soils, procurement and demand explain rice, wheat, millets, pulses, oilseeds, cotton, sugarcane, tea, coffee, rubber and horticulture belts. Climate change shifts suitability; diversification needs value chains, not crop advice alone.</p>`},
{id:'industry',title:'Industrial location',html:`<p>Industry locates by raw material, energy, water, labour, market, transport, capital, technology, agglomeration, policy and environmental constraints. Weight-losing industries favour inputs; perishables favour markets; footloose/high-value industries prioritise skills and connectivity.</p><p>Agglomeration shares suppliers, workers, services and knowledge but eventually creates congestion, land costs and pollution. Deindustrialisation or relocation can leave brownfields and unequal regions.</p><div class="exam-box"><b>Location answer:</b> traditional factors → changed technology/logistics → cluster/network effects → policy/ecology → current shift.</div>`},
{id:'transport',title:'Transport, trade and corridors',html:`<p>Routes follow terrain, passes, river crossings, coasts and settlements. Rail suits bulk/long distance; road offers flexibility; waterways are energy-efficient but constrained by depth/seasonality; air carries high-value/time-sensitive traffic. Ports need hinterland connection as much as harbour quality.</p><p>Corridors can lower costs and organise urban-industrial growth, but may create land conflict, ecological fragmentation or unequal bypassed regions. Evaluate network connectivity, not isolated projects.</p>`},
{id:'india',title:'Indian resource regions',html:`<p>Mineral-energy concentration in the plateau and sedimentary basins, fertile irrigated plains, plantation/high-value coasts and hills, and major industrial-urban corridors create regional opportunity and pressure. Resource states may export raw value yet bear displacement and pollution.</p><div class="concept-box"><b>Just resource federalism:</b> transparent allocation, local rights/benefit sharing, value addition where viable, restoration, diversified local economies and intergenerational stewardship.</div><p class="source-note">Map minerals, energy basins, crop belts, industrial corridors, ports and transport chokepoints.</p>`}
],recall:['Resource versus reserve?','Why can renewable resources be depleted?','Compare energy sources spatially.','Build an industrial location answer.','Map Indian resource–industry links.']};

BOOKS['08']={total:12,title:'Human & Settlement Geography',kicker:'Book 08 · People in space',dek:'Population distribution, migration, rural and urban settlements, and regional development.',prev:'07-resources-and-economic-geography.html',next:'09-hazards-and-changing-geography.html',sections:[
{id:'population',title:'Population distribution and change',html:`<p>Density reflects water, climate, relief, soil, jobs, transport, history and policy. Arithmetic density divides people by land; physiological density by arable land; agricultural density counts farmers per arable land. Scale can conceal crowded corridors within sparse regions.</p><p>Population changes through births, deaths and migration. Demographic transition moves from high birth/death rates to low rates through health, urbanisation, education, women’s agency and changing family economics. Age structure creates needs for schooling, jobs or ageing support.</p>`},
{id:'migration',title:'Migration and mobility',html:`<p>Push–pull is a starting point, not a full theory: households respond to jobs, wages, marriage, education, conflict, climate, networks, distance, costs and policy. Migration can be permanent, seasonal, circular, internal or international.</p><p>Origin gains remittances and risk diversification but may lose skills/care; destination gains labour and demand but strains housing/services if planning lags. Migrants face documentation, informality and social exclusion. Portability and rental/transit systems improve both efficiency and rights.</p>`},
{id:'rural',title:'Rural settlements and regional change',html:`<p>Compact settlements suit fertile plains, security and shared water; dispersed patterns occur with rugged relief, pastoralism or individual farmsteads. Site is the immediate physical location; situation is relative position within routes, markets and regions.</p><p>Rural–urban is a continuum shaped by commuting, services, remittances and peri-urban land change. Census/administrative labels may lag functional reality.</p>`},
{id:'urban',title:'Urbanisation and city systems',html:`<p>Urbanisation is rising urban share; urban growth is increase in urban population. Natural increase, migration and reclassification all contribute. Cities gain agglomeration economies but face congestion, pollution, heat, informality and inequality.</p><p>Land-use and transport co-create form. Low-density sprawl raises infrastructure and travel cost; transit-oriented, mixed-use planning can improve access if housing remains affordable. Urban flooding reflects extreme rain plus lost drainage/wetlands and impervious surfaces.</p><div class="chain">Jobs/services concentrate → migration and land demand → agglomeration gains + congestion → planning/finance response → inclusion or spatial exclusion.</div>`},
{id:'regions',title:'Regional inequality and place-based policy',html:`<p>Core regions attract capital and skills through cumulative advantage; peripheries may export labour/resources. Connectivity can spread opportunity or drain activity toward stronger centres. Place-based policy should diagnose the binding constraint—access, skills, institutions, ecology or market scale.</p><p>Border, mountain, island, tribal and coastal regions need differentiated planning. Comparable basic services plus locally adapted economic pathways balance equity and diversity.</p>`},
{id:'india',title:'India’s demographic and settlement geography',html:`<p>Dense Indo-Gangetic and coastal/delta belts contrast with mountains, desert and forest interiors. Migration connects rural origins to metros, industrial belts and construction/service centres. Metropolitan expansion crosses municipal boundaries, while many small towns lack finance and staff.</p><div class="exam-box"><b>Urban answer:</b> demographic driver → land/housing → mobility → services/ecology → finance/governance → vulnerable groups.</div><p class="source-note">Update from Census when available, official projections and surveys; never mix administrative town and urban agglomeration definitions.</p>`}
],recall:['Compare density measures.','Why is push–pull incomplete?','Site versus situation?','Urban growth versus urbanisation?','Build a spatially inclusive city answer.']};

BOOKS['09']={total:12,title:'Hazards & Changing Geography',kicker:'Book 09 · Dynamic risk',dek:'Geophysical hazards, climate extremes and changing water, ice, coasts and ecosystems.',prev:'08-human-and-settlement-geography.html',next:'10-map-and-atlas-workbook.html',sections:[
{id:'risk',title:'Hazard, exposure, vulnerability and disaster',html:`<p>A hazard is a potentially damaging process; exposure places people/assets in its path; vulnerability makes them susceptible; capacity reduces harm. A disaster occurs when impacts overwhelm coping. Risk is socially produced as well as physical.</p><div class="formula">Disaster risk ≈ Hazard × Exposure × Vulnerability ÷ Capacity</div><p>Prevention avoids risk, mitigation reduces it, preparedness enables response, response saves life, recovery restores and should build back better. Residual risk remains.</p>`},
{id:'tectonic',title:'Earthquakes, volcanoes and tsunamis',html:`<p>Earthquakes release accumulated strain along faults. Magnitude measures source energy; intensity records observed shaking/damage and varies by place. Depth, distance, geology, building and duration shape loss. Liquefaction affects saturated loose sediment.</p><p>Volcano type depends on magma viscosity, gas and tectonic setting. Tsunami risk combines source, bathymetry, coast shape, warning time and evacuation. Earthquakes cannot be precisely predicted; hazard zoning, codes, retrofitting, drills and lifelines reduce risk.</p>`},
{id:'hydro',title:'Cyclones, floods, droughts and landslides',html:`<p>Cyclone damage comes from wind, storm surge, waves and rain; surge is amplified by shallow funnel-shaped coasts and high tide. Floods may be riverine, flash, urban, coastal or glacial-lake related. Drought can be meteorological, agricultural, hydrological or socio-economic.</p><p>Landslides follow slope, rock, water and triggers. Engineering without drainage or debris-space planning increases danger. Multi-hazard cascades—earthquake damming a river, cyclone rain causing landslides—require system planning.</p>`},
{id:'ice',title:'Glaciers, ice caps and permafrost',html:`<p>Glacier mass balance is accumulation minus ablation; retreat concerns terminus position while thinning can occur without immediate retreat. Warming alters seasonal flow, slope stability and glacial lakes. Initial melt may raise discharge, later ice loss reduces dry-season buffering.</p><p>Sea level rises through land-ice melt and thermal expansion; floating sea-ice melt has little direct sea-level effect. Permafrost thaw damages infrastructure and releases carbon, reinforcing warming.</p>`},
{id:'coast',title:'Changing coasts, rivers and water bodies',html:`<p>Coasts shift with sediment supply, waves, currents, sea level, subsidence and structures. Dams trap sediment; ports and groynes interrupt drift; sand mining and wetland loss remove buffers. River channels migrate and lakes shrink/grow with climate, extraction, sediment and land use.</p><p>Remote sensing detects change but classification, season and resolution matter. Ground verification and time-series comparison prevent false conclusions.</p>`},
{id:'ecosystems',title:'Changing flora, fauna and landscapes',html:`<p>Species shift ranges and timing as temperature, rainfall, fire and land use change. Fragmentation blocks movement; invasives exploit disturbance. Forest-cover quantity does not automatically capture natural-forest quality or biodiversity.</p><div class="exam-box"><b>Changing-feature answer:</b> observed spatial change → physical and human drivers → ecosystem/livelihood effects → uncertainty → monitoring → adaptation/restoration.</div><p class="source-note">Update from NDMA, IMD, GSI, ISRO/NRSC and official disaster assessments.</p>`}
],recall:['Build risk from four components.','Magnitude versus intensity?','Classify droughts.','Land ice versus sea ice?','Explain a changing coast as sediment budget.']};

BOOKS['10']={total:12,title:'Map & Atlas Workbook',kicker:'Book 10 · Spatial recall',dek:'A repeatable India-and-world mapping system for places in news and static geography.',prev:'09-hazards-and-changing-geography.html',next:'11-prelims-master-book.html',sections:[
{id:'method',title:'The seven-layer map method',html:`<ol><li>Coordinates and neighbouring seas/countries.</li><li>Relief and plate/rock setting.</li><li>Rivers, lakes, straits and coasts.</li><li>Climate, winds, currents and vegetation.</li><li>Resources, crops and industries.</li><li>Population, cities and transport.</li><li>Hazards, protected areas and current change.</li></ol><p>Add layers progressively on blank maps. Location without relationships is fragile memory.</p>`},
{id:'india',title:'India compulsory map list',html:`<p>Practise: states/UTs and neighbours; latitude lines; Himalaya ranges/passes; plateau ranges/rifts; deserts; all major river systems, tributaries, dams and wetlands; coasts, gulfs, straits and islands; soil/rainfall/vegetation belts; crops, minerals and energy; ports, corridors and industrial regions; national parks/biosphere sites in news; seismic, cyclone, flood, drought and landslide zones.</p>`},
{id:'world',title:'World compulsory map list',html:`<p>Plates, ridges, trenches, hotspots, mountain belts and deserts; major rivers/lakes; seas, gulfs, straits and canals; ocean currents/upwelling; climate and biome belts; resources and industrial cores; conflict/trade chokepoints; polar and glacier regions.</p>`},
{id:'place',title:'Place-in-news card',html:`<p>For every place, record: country/region; coordinates/relative location; neighbours; physical setting; strategic/economic/ecological significance; associated current event; one map sketch. If it cannot be placed in 15 seconds, it is not learned.</p><div class="concept-box"><b>Relational memory:</b> “west of X, on Y river, leeward of Z range, connected by A strait” survives better than a dot.</div>`},
{id:'drills',title:'Weekly drills',html:`<p>Monday India physical; Tuesday rivers/coasts; Wednesday world physical; Thursday resources; Friday current places; Saturday 20 location statements; Sunday redraw errors. Use north arrow, rough scale only when relevant, clear labels and no decorative detail.</p>`},
{id:'questions',title:'Self-test prompts',html:`<ol><li>Trace a monsoon branch from ocean to rain shadow.</li><li>Mark five convergent-margin hazard zones.</li><li>Link Indian coal/iron belts with industry and ports.</li><li>Mark ten straits and state what they connect.</li><li>Map a river from source to delta with tributaries, cities and hazards.</li></ol><p class="source-note">Use a reliable current atlas plus official thematic maps. Redraw rather than tracing.</p>`}
],recall:['Name all seven layers.','Draw India physical in five minutes.','Place ten current locations relationally.','Trace one commodity chain spatially.','Mark five multi-hazard coasts.']};

BOOKS['11']={total:12,title:'Prelims Master Book',kicker:'Book 11 · Elimination with maps',dek:'High-yield distinctions, statement logic and original Geography MCQs with explanations.',prev:'10-map-and-atlas-workbook.html',next:'12-mains-answer-writing-manual.html',sections:[
{id:'traps',title:'How Geography statements mislead',html:`<p>Common traps reverse wind/current direction, confuse cause and location, use a true global rule without local exceptions, interchange weathering and erosion, or attach the correct feature to the wrong plate boundary. Draw a thumbnail map or causal arrow before selecting.</p><div class="warning-box"><b>Words to test:</b> only, always, directly, all, exclusively, north/south, windward/leeward, upper/lower course, source/mouth.</div>`},
{id:'pairs',title:'High-yield distinctions',html:`<table><tr><th>Pair</th><th>Difference</th></tr><tr><td>Crust / lithosphere</td><td>Compositional / mechanical layer</td></tr><tr><td>Weathering / erosion</td><td>Breakdown in place / removal</td></tr><tr><td>Magma / lava</td><td>Below / at surface</td></tr><tr><td>Focus / epicentre</td><td>Source within / point above</td></tr><tr><td>Magnitude / intensity</td><td>Source energy / observed effects</td></tr><tr><td>Delta / estuary</td><td>Depositional distributaries / tidal drowned mouth</td></tr><tr><td>Thermocline / halocline</td><td>Rapid temperature / salinity gradient</td></tr><tr><td>Spring / neap tide</td><td>Aligned / right-angle lunar-solar forcing</td></tr><tr><td>Humidity / relative humidity</td><td>Vapour amount / saturation ratio</td></tr><tr><td>Weather / climate</td><td>Short state / long distribution</td></tr><tr><td>Aquifer / aquitard</td><td>Transmits well / poorly</td></tr><tr><td>Urban growth / urbanisation</td><td>Number rise / share rise</td></tr><tr><td>Hazard / disaster</td><td>Potential process / severe realised disruption</td></tr></table>`},
{id:'mcq1',title:'Practice — physical geography',html:`<p><b>1.</b> S waves pass through the outer core; P waves do not. <b>Answer: both false.</b> P passes liquids; S does not.</p><p><b>2.</b> Oceanic–continental convergence can produce a trench and continental volcanic arc. <b>Correct.</b></p><p><b>3.</b> Every sedimentary rock contains fossils. <b>False.</b> Preservation depends on origin and history.</p><p><b>4.</b> Relative humidity may rise without addition of water vapour. <b>Correct.</b> Cooling can raise it.</p><p><b>5.</b> Tropical cyclones commonly form exactly at the equator. <b>False.</b> Coriolis is too weak.</p><p><b>6.</b> A western boundary current is generally slower than its eastern counterpart. <b>False.</b> Usually narrow and fast.</p>`},
{id:'mcq2',title:'Practice — India and resources',html:`<p><b>7.</b> Black soil is closely associated with Deccan basalt and has high moisture retention. <b>Correct.</b></p><p><b>8.</b> All major Peninsular rivers form deltas. <b>False.</b> Narmada/Tapi form estuarine mouths.</p><p><b>9.</b> High annual rainfall necessarily means year-round water security. <b>False.</b> Seasonality/storage/access matter.</p><p><b>10.</b> Port location depends only on harbour depth. <b>False.</b> Hinterland and connectivity are central.</p><p><b>11.</b> Renewable energy is spatially uniform. <b>False.</b> Resource quality, land and grids vary.</p><p><b>12.</b> Physiological density uses arable land as denominator. <b>Correct.</b></p>`},
{id:'mcq3',title:'Practice — hazards and change',html:`<p><b>13.</b> Earthquake magnitude varies from one observation town to another. <b>False.</b> Intensity varies; event magnitude is a source measure.</p><p><b>14.</b> Melting floating sea ice is the main direct cause of sea-level rise. <b>False.</b> Land ice and thermal expansion dominate.</p><p><b>15.</b> Embankments may transfer flood risk downstream. <b>Correct.</b></p><p><b>16.</b> Forest-cover increase necessarily proves natural-biodiversity recovery. <b>False.</b> Plantation and quality differ.</p><p><b>17.</b> Dams can contribute to coastal erosion by trapping sediment. <b>Correct.</b></p><p><b>18.</b> Drought is only a rainfall deficit. <b>False.</b> Agricultural, hydrological and socio-economic drought exist.</p>`},
{id:'revision',title:'Twenty-one-day revision',html:`<p>Days 1–6 physical books; 7–9 India/resources/human; 10–12 hazards and atlas; 13–16 mixed MCQs; 17–19 only error maps and causal chains; 20–21 timed tests. Classify errors as map, mechanism, qualifier, pair-confusion or current-source gap.</p><div class="exam-box"><b>Daily minimum:</b> one blank map, five causal arrows, fifteen statements.</div>`}
],recall:['List ten trap pairs.','Solve six questions without explanations.','Draw five thumbnail maps.','Classify your last ten errors.','Explain why a true generalisation may fail locally.']};

BOOKS['12']={total:12,title:'Mains Answer-Writing Manual',kicker:'Book 12 · Geography into GS-I marks',dek:'Directive decoding, causal diagrams, maps, model structures and a thematic question bank.',prev:'11-prelims-master-book.html',next:null,sections:[
{id:'demand',title:'Decode the question',html:`<p>Identify directive, spatial scale, process and outcome. “Account for distribution” needs location plus causal factors; “explain phenomenon” needs mechanism; “examine changes” needs baseline, drivers, spatial pattern and effects; “evaluate” needs criteria and judgment.</p>`},
{id:'structure',title:'Universal geography answer',html:`<ol><li>Define and locate.</li><li>Draw a small relevant map/diagram.</li><li>Explain physical mechanism.</li><li>Add human drivers/interactions.</li><li>Show regional variation or examples.</li><li>Discuss effects and vulnerable groups.</li><li>Offer scale-appropriate planning.</li></ol><div class="chain">Where? → Why there? → How changing? → Who/what affected? → What response at what scale?</div>`},
{id:'visuals',title:'Maps and diagrams that earn space',html:`<p>Use plate-section sketches, pressure/wind maps, cyclone cross-section, monsoon flow, river long profile, soil catena, resource-location triangle, urban expansion and risk equation. Labels must state causal verbs. India/world outline maps should carry 4–7 accurate points, not artistic coastlines.</p>`},
{id:'models',title:'Model answer skeletons',html:`<h3>Why are Himalayan disasters increasingly multi-causal?</h3><p>Young tectonics and steep fractured relief form baseline hazard; extreme rain, glacier/lake change and seismicity trigger events; road cutting, drainage blockage, river encroachment and concentrated tourism raise exposure. Cascades connect landslide, damming and flash flood. Recommend cumulative basin/slope assessment, codes, monitoring, carrying capacity and local preparedness.</p><h3>Explain uneven monsoon rainfall.</h3><p>Locate broad pattern; explain branch paths, orography/rain shadow, Bay depressions, monsoon trough and distance/continentality; add intra-seasonal breaks and ocean coupling; show consequences for crops/water and region-specific adaptation.</p><h3>Industrial location is becoming network-based rather than raw-material based. Discuss.</h3><p>Acknowledge weight-losing industries; show logistics, skills, market, suppliers, knowledge and digital networks; use Indian clusters/corridors; note energy, water, congestion and policy; conclude with resilient multimodal regional strategy.</p>`},
{id:'questions',title:'GS-I question bank',html:`<ol><li>Plate tectonics explains both relief and hazard concentration. Discuss.</li><li>How do upper-air circulation and ocean conditions shape the Indian monsoon?</li><li>Examine the consequences of changing sediment budgets for Indian coasts.</li><li>Why does groundwater scarcity persist in regions with substantial rainfall?</li><li>Account for the distribution of major mineral-industrial regions of India.</li><li>Urban floods are planning disasters triggered by meteorology. Examine.</li><li>Explain how glacier change creates both short- and long-term water risks.</li><li>Migration is a spatial household strategy, not simply rural distress. Discuss.</li><li>How can infrastructure corridors widen and reduce regional inequality simultaneously?</li><li>Differentiate hazard control from vulnerability reduction using Indian examples.</li></ol>`},
{id:'rubric',title:'Self-review rubric',html:`<table><tr><th>Criterion</th><th>Check</th></tr><tr><td>Spatial</td><td>Map/location/scale accurate?</td></tr><tr><td>Mechanism</td><td>Causal sequence correct?</td></tr><tr><td>Integration</td><td>Physical and human factors joined?</td></tr><tr><td>Variation</td><td>Regional exceptions/examples?</td></tr><tr><td>Change</td><td>Trend and drivers distinguished?</td></tr><tr><td>Response</td><td>At basin/coast/city/region scale?</td></tr></table><p class="source-note">Use current official data only when period/source are known. One accurate map often outperforms three vague examples.</p>`}
],recall:['Write the seven-step answer frame.','Draw five GS diagrams.','Outline two questions in seven minutes.','Review one answer with all six criteria.','Explain why scale determines policy.']};
