BOOKS['02']={total:12,title:'Earth & Geomorphology',kicker:'Book 02 · The solid Earth',dek:'Earth structure, plate motion, rocks, weathering and the landforms they create.',prev:'01-syllabus-and-master-roadmap.html',next:'03-atmosphere-and-climate.html',sections:[
{id:'earth',title:'Origin, interior and evidence',html:`<p>Earth differentiated into crust, mantle and core as denser material sank. The lithosphere is rigid crust plus uppermost mantle; the asthenosphere beneath deforms slowly. Continental crust is thicker and lighter than oceanic crust. Temperature, pressure and density rise inward.</p><p>Direct evidence comes from shallow mines, boreholes and volcanic material; most knowledge is indirect. Seismic P waves pass through solids and liquids, while S waves do not pass through liquids. Their speed, refraction and shadow zones reveal boundaries and the liquid outer core. Earth’s magnetic field is linked to motion in the conducting outer core.</p><div class="exam-box"><b>Prelims anchors:</b> compositional layers are not identical to mechanical layers; S-wave absence, not merely slowing, indicates liquid.</div>`},
{id:'plates',title:'Plate tectonics',html:`<p>Lithospheric plates move over the asthenosphere through mantle convection, slab pull and ridge push. Divergent boundaries create crust at ridges and rifts; convergent boundaries destroy or thicken crust through subduction or collision; transform boundaries slide laterally.</p><table><tr><th>Boundary</th><th>Features</th></tr><tr><td>Ocean–ocean convergence</td><td>Trench, island arc, earthquakes</td></tr><tr><td>Ocean–continent</td><td>Trench, continental volcanic chain</td></tr><tr><td>Continent–continent</td><td>Fold mountains, plateau, earthquakes</td></tr><tr><td>Divergence</td><td>Ridge/rift, shallow quakes, volcanism</td></tr></table><p>Matching coasts, fossils and rocks, palaeoclimate, magnetic stripes and ocean-floor age patterns support the theory.</p>`},
{id:'rocks',title:'Rocks and the rock cycle',html:`<p>Igneous rocks crystallise from magma/lava; intrusive cooling is slow and coarse, extrusive rapid and fine. Sedimentary rocks form through deposition and lithification or chemical/organic processes and commonly preserve strata/fossils. Metamorphic rocks form when heat, pressure or fluids alter rock without full melting.</p><div class="chain">Uplift → weathering/erosion → deposition → lithification → heat/pressure → metamorphism → melting → magma → crystallisation.</div><p>Rock influences relief, soil, groundwater, minerals and construction. The cycle has multiple pathways, not a compulsory circle.</p>`},
{id:'weathering',title:'Weathering, mass movement and erosion',html:`<p>Weathering breaks rock in place—mechanically, chemically or biologically. Climate, rock, slope, vegetation and time control it. Mass movement transfers material downslope under gravity; saturation, toe cutting, road excavation, deforestation and earthquakes can trigger failure.</p><div class="concept-box"><b>Sequence:</b> weathering prepares material; mass movement shifts it downslope; erosion entrains and transports it. They interact but are not synonyms.</div>`},
{id:'landforms',title:'Fluvial, glacial, aeolian, coastal and karst landforms',html:`<p>Rivers incise valleys, gorges, potholes and waterfalls and build meanders, floodplains, levees, oxbow lakes and deltas. Glaciers create U-valleys, cirques, arêtes and moraines. Wind forms deflation hollows, yardangs and dunes. Waves create cliffs, caves, arches, stacks, beaches and spits. Limestone solution forms sinkholes and caves.</p><div class="warning-box"><b>Landform questions are process questions.</b> Attach each feature to agent, erosion/deposition, climatic setting and sequence.</div>`},
{id:'india',title:'Indian application',html:`<p>India’s relief reflects the northward Indian Plate collision, stable but faulted Peninsular block, sediment-filled plains and evolving coasts/islands. Himalayan earthquakes and landslides combine active tectonics, steep fractured slopes, intense rain and construction. Plateau rifts, basalt and ancient rocks influence rivers, soils and minerals.</p><p class="source-note">Map plates, ridges, trenches, fold belts; Indian seismic zones, Himalayan divisions, rifts and volcanic/karst regions.</p>`}
],recall:['How do seismic waves reveal the core?','Compare boundary settings.','Trace three rock-cycle paths.','Differentiate weathering, movement and erosion.','Explain an Indian hazard through tectonics and land use.']};

BOOKS['03']={total:12,title:'Atmosphere & Climate',kicker:'Book 03 · The moving air',dek:'Radiation, pressure, circulation, weather systems, monsoon and climate variability.',prev:'02-earth-and-geomorphology.html',next:'04-oceans-and-water.html',sections:[
{id:'structure',title:'Composition and layers',html:`<p>Nitrogen and oxygen dominate dry air; variable water vapour drives clouds, precipitation and latent heat. Greenhouse gases absorb outgoing longwave radiation. Aerosols scatter/absorb radiation and seed clouds.</p><p>The troposphere contains weather and generally cools upward. The stratosphere warms upward as ozone absorbs ultraviolet radiation. The mesosphere and thermosphere lie above; ionised upper air affects communication.</p>`},
{id:'heat',title:'Heat budget and temperature',html:`<p>Incoming shortwave energy is reflected, scattered or absorbed; Earth emits longwave radiation, some returned downward by greenhouse gases. Latitudinal surplus and deficit drive circulation.</p><p>Insolation varies with angle, day length, cloud and albedo. Latitude, altitude, continentality, currents, wind and slope modify temperature. Inversions suppress mixing and trap pollution.</p><div class="concept-box"><b>Natural greenhouse effect enables life; enhanced greenhouse effect shifts energy balance. Ozone depletion is distinct.</b></div>`},
{id:'circulation',title:'Pressure belts, winds and jets',html:`<p>Pressure gradients initiate wind; Coriolis deflects right in the Northern Hemisphere and left in the Southern, zero at the equator. Friction turns surface winds across isobars. Global circulation creates trades, westerlies and polar easterlies.</p><p>ITCZ migration shifts rain. Jet streams steer weather; Rossby waves and blocking prolong patterns. Sea/land and mountain/valley breezes arise from differential heating.</p>`},
{id:'weather',title:'Humidity, fronts and precipitation',html:`<p>Relative humidity changes with vapour and temperature. Stability controls vertical motion. Convectional rain follows heating; orographic rain follows forced uplift and rain shadow; frontal rain follows converging air masses.</p><p>Tropical cyclones need warm deep ocean, moisture, Coriolis and limited shear; temperate cyclones form along fronts and draw energy from horizontal temperature contrast.</p>`},
{id:'monsoon',title:'Indian monsoon',html:`<p>The monsoon combines land–sea contrast, ITCZ shift, cross-equatorial flow, Tibetan-Himalayan heating, jet streams and coupled ocean variability. Arabian Sea and Bay branches interact with relief and lows. Breaks reflect trough shifts; retreating flow gives southeast India crucial rain.</p><div class="chain">Thermal state + pressure + cross-equatorial flow + upper air + synoptic systems → onset, distribution and breaks.</div><p>ENSO, Indian Ocean Dipole and MJO influence but never mechanically determine every season.</p>`},
{id:'change',title:'Climate types, variability and change',html:`<p>Know major climate types through temperature, rainfall seasonality, mechanism, vegetation and map. Climate variability operates from days to decades; climate change shifts long-term distributions and extreme-event probability.</p><div class="exam-box"><b>Extreme answer:</b> mechanism → exposure → vulnerability → observed trend → warning → resilient land use/infrastructure.</div><p class="source-note">Update from IMD and WMO/IPCC primary summaries.</p>`}
],recall:['Why does the stratosphere warm upward?','Trace heat budget to circulation.','Compare cyclone types.','Explain monsoon beyond simple land heating.','Weather event versus climate change?']};

BOOKS['04']={total:12,title:'Oceans & Water',kicker:'Book 04 · The blue planet',dek:'Ocean relief, circulation, tides, marine resources and the water cycle.',prev:'03-atmosphere-and-climate.html',next:'05-soils-biomes-and-environment.html',sections:[
{id:'relief',title:'Ocean-floor relief',html:`<p>Continental shelves are shallow submerged margins; slopes descend to deep basins; rises collect sediment on many passive margins. Abyssal plains are deep and flat; ridges create crust; trenches mark subduction; seamounts record volcanism. Legal continental shelf and EEZ concepts do not equal the visible landform.</p>`},
{id:'properties',title:'Temperature, salinity and density',html:`<p>Surface temperature follows latitude, currents, winds and upwelling. Salinity reflects evaporation, rain, rivers and ice. Both control density and stratification. Strong stratification limits mixing; upwelling brings cold nutrient-rich water and supports fisheries.</p>`},
{id:'currents',title:'Circulation and climate',html:`<p>Winds, Coriolis and continents produce gyres. Western boundary currents are often narrow, fast and warm; eastern ones broader, slower and linked to upwelling. Density-driven deep circulation connects basins.</p><div class="chain">Trade-wind change ↔ thermocline/upwelling shift ↔ Pacific SST ↔ convection and global ENSO teleconnections.</div>`},
{id:'coast',title:'Waves, tides and coasts',html:`<p>Wind waves transfer energy; tsunamis are long waves from sudden displacement, not tides. Lunar and solar gravity drive tides: spring near new/full moon, neap near quarter phases. Longshore drift redistributes sediment, so hard structures can transfer erosion down-coast.</p>`},
{id:'water',title:'Hydrology and groundwater',html:`<p>The water cycle links evaporation, transpiration, precipitation, infiltration, runoff and storage. Basin discharge depends on rainfall intensity, soil, slope, vegetation, prior moisture and urbanisation. Aquifers store/transmit water; over-pumping can dry streams, induce salinity and cause subsidence.</p>`},
{id:'resources',title:'Marine resources and governance',html:`<p>Oceans provide fish, energy, minerals, transport and climate regulation. Overfishing, habitat loss, warming, acidification, deoxygenation and pollution interact. Blue economy means sustainable use with ecosystem and livelihood integrity.</p><div class="exam-box"><b>Coastal answer:</b> sediment cell + ecosystem + hazard + livelihood + infrastructure + governance.</div><p class="source-note">Map currents, ridges, trenches, straits, upwelling and Indian basins.</p>`}
],recall:['Legal versus geomorphic shelf?','How do salinity and heat move water?','Explain ENSO.','Why can seawalls shift erosion?','Trace over-pumping impacts.']};

BOOKS['05']={total:12,title:'Soils, Biomes & Environment',kicker:'Book 05 · Living landscapes',dek:'Soil systems, global biomes, ecosystem processes and biodiversity geography.',prev:'04-oceans-and-water.html',next:'06-physical-geography-of-india.html',sections:[
{id:'soil',title:'Soil formation and profile',html:`<p>Soil develops through parent material, climate, organisms, relief and time. Weathering supplies minerals; organisms build humus; water transfers material between horizons. Texture controls water/aeration, structure controls aggregation and pH affects nutrients.</p><p>Laterisation follows intense leaching; podzolisation cool acidic conditions; calcification drylands; salinisation evaporation and poor drainage.</p>`},
{id:'degradation',title:'Degradation and conservation',html:`<p>Sheet, rill, gully and wind erosion remove soil. Nutrient mining, compaction, acidification, salinity and contamination degrade function without obvious loss. Contours, terraces, cover, agroforestry, shelterbelts and watershed treatment must match slope and climate.</p><div class="concept-box"><b>Land degradation is broader than desertification; desertification is dryland degradation from climatic variation and human activity.</b></div>`},
{id:'ecosystem',title:'Ecosystem flows',html:`<p>Energy flows through producers, consumers and decomposers with losses; matter cycles. Food webs offer alternative pathways. Primary succession begins without developed soil; secondary where soil/propagules remain. Feedbacks can push ecosystems across thresholds.</p>`},
{id:'biomes',title:'World biomes',html:`<p>Equatorial forest is warm, wet and layered; savanna seasonal and fire-adapted; deserts conserve water; Mediterranean vegetation tolerates dry summers/fire; temperate grasslands often have fertile soils; taiga is coniferous; tundra has permafrost. Mountains compress zones by altitude.</p>`},
{id:'biodiversity',title:'Biodiversity geography',html:`<p>Biodiversity spans genes, species and ecosystems. Tropical richness reflects energy, stability and history; isolation creates endemism. In-situ conservation retains ecological relationships; ex-situ is backup. Corridors require landscape and community design.</p><div class="exam-box"><b>Hotspot:</b> high endemism plus high habitat loss—not merely high species count.</div>`},
{id:'india',title:'Indian soils and vegetation',html:`<p>Major soils include alluvial, black, red/yellow, lateritic, arid, mountain/forest, saline and peaty types. Vegetation ranges from evergreen and deciduous through thorn and montane to mangrove, driven by rainfall, seasonality, altitude and salinity.</p><p class="source-note">Map soil belts, vegetation, hotspots and landscape corridors.</p>`}
],recall:['Five soil factors?','Erosion versus degradation?','Energy versus nutrient flow?','Biome adaptation to seasonality?','Map Indian soils with issues.']};

BOOKS['06']={total:12,title:'Physical Geography of India',kicker:'Book 06 · The Indian subcontinent',dek:'Physiography, drainage, monsoon, soils, vegetation and regional interactions.',prev:'05-soils-biomes-and-environment.html',next:'07-resources-and-economic-geography.html',sections:[
{id:'divisions',title:'Structure and physiography',html:`<p>The young active Himalaya, deep alluvial Northern Plains, ancient Peninsular Plateau, arid west, coastal plains and islands reflect tectonics, sediment and marine processes. Relief controls climate, rivers, soils, hazards, settlement and resources.</p><p>These are connected: Himalayan sediment builds plains/deltas; plateau scarps steer rivers; coasts receive catchment sediment and wave energy.</p>`},
{id:'mountains',title:'Himalaya and Northeast',html:`<p>Foothill, Lesser, Greater and trans-Himalayan systems vary in rock and height. Valleys, passes and gorges structure access. Eastern hills curve south and receive intense rain. Young geology, steep slopes, earthquakes, glaciers and construction compound risk.</p>`},
{id:'plateau',title:'Plateau, desert, coasts and islands',html:`<p>Central Highlands and Deccan include shields, rifts, basalt and scarps. Western Ghats are high and continuous; Eastern Ghats lower and discontinuous. Thar aridity reflects subsidence, continentality, relief and monsoon variability. Western coasts are generally narrow; eastern broader and deltaic, with exceptions. Islands include continental, coral and volcanic origins.</p>`},
{id:'rivers',title:'Drainage and river behaviour',html:`<p>Himalayan rivers are often perennial, long and sediment-heavy; Peninsular systems rely more on seasonal rain and older relief. Floodplains migrate. Embankments protect locally but may raise/transfer risk. River-linking involves ecology, displacement, sediment, energy, federal sharing and uncertain climate.</p><div class="exam-box"><b>River answer:</b> geology → water regime → sediment → channel/floodplain → uses → intervention → downstream coast.</div>`},
{id:'climate',title:'Indian climate regions',html:`<p>Relief and seasonal circulation generate enormous variety: western disturbances in the northwest, pre-monsoon storms, southwest monsoon, rain shadows and retreating-monsoon rain in the southeast. High annual rain can coexist with water scarcity due to seasonality, storage and access.</p>`},
{id:'integration',title:'Soils, vegetation and connected regions',html:`<p>Soils and vegetation follow geology, monsoon and relief but are widely transformed. Basin, coast and mountain planning must complement administrative boundaries. Core map layers: physiography, passes, rivers, wetlands, soil, rainfall, vegetation, coasts, islands and hazards.</p><p class="source-note">Use Survey/official thematic maps and current IMD/ISRO material for changes.</p>`}
],recall:['How do divisions interact?','Why is Himalayan risk cumulative?','Compare coasts.','Evaluate embankments basin-wide.','Draw ten physical layers.']};
