BOOKS['02']={total:13,title:'Ancient India',kicker:'Book 02 · Foundations and transformations',dek:'Sources, Harappans, Vedic society, states, empires, economy, religion and regional cultures.',prev:'01-syllabus-and-master-roadmap.html',next:'03-medieval-india.html',sections:[
{id:'sources',title:'Sources and how to use them',html:`<p>Archaeology—settlements, pottery, tools, burials, coins and inscriptions—reveals material life but needs context. Literary sources preserve ideas and memory but reflect genre, patronage and later editing. Foreign accounts observe selectively. Strong conclusions triangulate sources.</p><table><tr><th>Source</th><th>Strength</th><th>Caution</th></tr><tr><td>Inscription</td><td>Dating, titles, grants, public claims</td><td>Royal praise and formula</td></tr><tr><td>Coin</td><td>Economy, authority, iconography</td><td>Circulation ≠ exact border</td></tr><tr><td>Text</td><td>Norms, ideas, narrative</td><td>Prescription ≠ social reality</td></tr><tr><td>Archaeology</td><td>Everyday material pattern</td><td>Interpretation and preservation bias</td></tr></table>`},
{id:'harappa',title:'Harappan civilisation',html:`<p>Harappan urbanism developed across the Indus and adjoining regions with planned streets, drainage, standardised weights, craft specialisation, long-distance trade and diverse settlement hierarchy. Major sites differed: there was no single identical city plan.</p><p>The script remains undeciphered, limiting claims about language or government. Agriculture, pastoralism and river/maritime exchange sustained cities. Religious interpretation must be cautious: seals and figurines are evidence, not direct proof of later deities.</p><p>Urban decline was regionally uneven and likely involved river change, aridity, trade shifts and social adaptation rather than one invasion. Harappan populations and practices transformed rather than simply vanished.</p>`},
{id:'vedic',title:'Vedic transformations',html:`<p>Early Vedic society in the northwest was pastoral-agricultural, lineage based and politically organised through chiefs and assemblies. Later expansion into the Ganga plains accompanied iron use, settled agriculture, surplus, larger kingdoms and stronger social stratification.</p><p>Varna ideals hardened in texts but jati and actual social practice were complex and regional. Ritual authority and royal power reinforced each other, while Upanishadic thought questioned ritual centrality through knowledge and self.</p><div class="exam-box"><b>Change frame:</b> geography and technology → surplus → political scale → social differentiation → religious response.</div>`},
{id:'states',title:'Mahajanapadas, cities and new religions',html:`<p>By the sixth century BCE, territorial states and oligarchic republics coexisted. Iron tools, agriculture, taxation, trade, coin use and towns supported state formation. Magadha benefited from fertile plains, rivers, elephants, iron access and ambitious rulers.</p><p>Buddhism and Jainism emerged amid social-economic change and older renunciatory traditions. Both questioned Vedic sacrifice, stressed ethical conduct and built monastic communities; they differed in doctrine and discipline. Merchant and ruler patronage helped institutions spread along routes.</p>`},
{id:'maurya',title:'Mauryan state and Ashoka',html:`<p>The Mauryan Empire connected a large territory through provincial centres, taxation, officials, army and roads, but governance intensity varied. The Arthashastra is a normative political text with complex dating; Megasthenes is an outsider; Ashokan edicts are direct public communications. They should not be collapsed into one administrative snapshot.</p><p>After Kalinga, Ashoka’s dhamma promoted ethical restraint, welfare, respect and non-violence without simply abolishing state power or declaring one sect as a modern state religion. Edicts used languages and scripts suited to regions.</p>`},
{id:'post',title:'Post-Mauryan connections and regional states',html:`<p>Indo-Greeks, Shakas, Kushanas, Satavahanas and others connected Central Asia, north and Deccan. Coinage, routes, ports and Roman/Asian trade supported urban and craft centres. Mahayana Buddhism and image traditions expanded in this cosmopolitan setting.</p><p>Sangam literature and archaeology illuminate early historic Tamilakam—chiefdoms/kingdoms, agriculture, cattle, war, bards, ports and overseas trade. Textual landscapes link ecology with livelihood and emotion but are literary conventions as well as evidence.</p>`},
{id:'gupta',title:'Gupta age and early-medieval transition',html:`<p>Gupta rulers built an influential northern empire with Sanskrit political culture, coinage, learning, art and religious patronage. Calling it a universal “golden age” hides social hierarchy, regional variation and uneven prosperity. Science, mathematics, literature and temple forms flourished in wider networks.</p><p>Land grants to religious and administrative beneficiaries, regional kingdoms and local intermediaries reshaped authority after the Guptas. Pallavas, Chalukyas, Rashtrakutas and others sponsored temples, trade and agrarian expansion. The period is best seen as regionalisation and new integration, not simple decline.</p><p class="source-note">Map major sites, mahajanapadas, imperial cores, routes, ports, caves and universities.</p>`}
],recall:['Why triangulate source types?','List Harappan features and cautions.','Explain Vedic change structurally.','Why did Magadha rise?','Assess “golden age” critically.']};

BOOKS['03']={total:13,title:'Medieval India',kicker:'Book 03 · Regions, empires and cultures',dek:'Political formations, agrarian change, trade, Sultanate, Vijayanagara, Mughals and devotional movements.',prev:'02-ancient-india.html',next:'04-indian-art-and-culture.html',sections:[
{id:'early',title:'Early-medieval regionalisation',html:`<p>From roughly the seventh century, regional kingdoms, agrarian expansion, land grants, temple institutions and vernacular cultures reshaped India. Gurjara-Pratiharas, Palas, Rashtrakutas and many local powers competed and connected. Chola state power rested on agrarian revenue, military organisation, temples, local assemblies and maritime links.</p><p>“Feudalism” is a debated analytical label; GS needs the evidence—landed intermediaries, service grants, peasant obligations, local authority and trade variation—rather than doctrinal historiography.</p>`},
{id:'sultanate',title:'Delhi Sultanate',html:`<p>Mamluk, Khalji, Tughlaq, Sayyid and Lodi dynasties ruled with changing territorial reach. The iqta assigned revenue collection in return for service but was not necessarily hereditary private ownership. Persianate administration interacted with Indian elites and local institutions.</p><p>Alauddin Khalji’s market and revenue measures served military-fiscal aims; Muhammad bin Tughlaq’s ambitious experiments failed unevenly due to scale, trust, enforcement and context, not simply personal eccentricity. Technology, cavalry, textiles, paper and expanding towns influenced economy and culture.</p>`},
{id:'regions',title:'Vijayanagara and regional states',html:`<p>Vijayanagara combined fortified urbanism, temple-centred sacred geography, agrarian irrigation, nayaka military service and coastal trade. Bahmani and successor states developed Deccan political-cultural forms. Bengal, Gujarat, Malwa, Kashmir, Odisha and others were active centres, not peripheral footnotes.</p><p>Travel accounts describe markets, court and cities but must be checked against archaeology and inscriptions. The 1565 battle weakened the capital’s political centrality, yet regional successor powers and culture continued.</p>`},
{id:'mughal',title:'Mughal state and economy',html:`<p>The Mughal Empire combined a central imperial household with mansabdari ranking and jagir revenue assignments. Mansab indicated status and service obligation; jagir was assigned revenue, not necessarily land ownership. Zamindars were varied local right-holders/intermediaries and political actors.</p><p>Akbar expanded through warfare, alliance and administrative integration; sulh-i kul expressed broad peace/tolerance in imperial governance. Revenue assessment under zabt suited measured stable areas but other systems existed. Agrarian surplus sustained cities, crafts and large armies; Indian Ocean and overland trade linked merchants globally.</p>`},
{id:'society',title:'Society, technology and environment',html:`<p>Peasants, pastoralists, forest communities, artisans, merchants, soldiers, scholars and elites occupied overlapping worlds. Caste adapted to occupations and regions; women’s roles varied by class, community and lifecycle. Irrigation, crops from global exchange, textile technologies and gunpowder altered production and power.</p><p>State expansion converted forests to fields but forest polities retained autonomy and trade. Famines and scarcity emerged from rainfall shocks interacting with entitlement, war and markets.</p>`},
{id:'bhakti',title:'Bhakti and Sufi traditions',html:`<p>Bhakti traditions ranged from Tamil Alvars/Nayanars to Virashaivas, Vaishnava movements, nirguna poet-saints and regional communities. They used vernacular expression and often challenged ritual/status, yet their social effects varied and institutions could develop hierarchy.</p><p>Sufi silsilas organised around teachers, khanqahs and devotional practice. Chishti and other orders differed in relations with rulers and law. Bhakti–Sufi interaction encouraged shared cultural spaces, but should not be reduced to a single uniform “syncretism.”</p>`},
{id:'eighteenth',title:'Mughal decline and the eighteenth century',html:`<p>After Aurangzeb, succession conflict, fiscal-military strain, jagir pressures, regional assertion and invasions weakened imperial control. Bengal, Awadh and Hyderabad became successor states; Marathas, Sikhs, Jats and others built new power. Mughal symbols and revenue practices continued.</p><div class="concept-box"><b>The eighteenth century was political decentralisation and commercial-regional reconfiguration—not a void awaiting British rule.</b></div><p class="source-note">Map imperial centres, ports, routes, regional states, temples, Sufi centres and battle zones.</p>`}
],recall:['What does regionalisation mean?','Iqta versus ownership?','Mansab, jagir and zamindar?','Why avoid uniform Bhakti claims?','Reinterpret the eighteenth century.']};

BOOKS['04']={total:13,title:'Indian Art & Culture',kicker:'Book 04 · Forms, ideas and patronage',dek:'Architecture, sculpture, painting, literature, religion, music, dance and crafts from ancient to modern.',prev:'03-medieval-india.html',next:'05-british-conquest-and-colonial-state.html',sections:[
{id:'method',title:'How to study culture',html:`<p>For every cultural form record period, geography, material/technique, patron/community, formal features, religious-social function, cross-cultural influence and one representative example. Style is not a date list; it is a solution shaped by material, ritual, technology and patronage.</p>`},
{id:'architecture',title:'Architecture',html:`<p>Harappan cities emphasised civic planning, brick and water systems. Buddhist architecture developed stupas, railings, gateways, chaitya halls and viharas; rock-cut traditions evolved from simple halls to elaborate monasteries and temples.</p><p>Nagara temples generally use curving shikhara and northern plans; Dravida temples use pyramidal vimana and increasingly monumental gateways; Vesara is a convenient mixed/deccan label, not a rigid third box. Sultanate and Mughal forms developed arches, domes, vaults, minarets, gardens and surface decoration through Indian and Persianate skills. Colonial styles included neoclassical, Gothic, Indo-Saracenic and modern planning.</p>`},
{id:'sculpture',title:'Sculpture and iconography',html:`<p>Mauryan polish, yaksha traditions, stupa reliefs and later Gandhara/Mathura schools show changes in material and representation. Gandhara used Hellenistic-influenced drapery and schist; Mathura drew on indigenous forms and red sandstone; both contributed to Buddha images.</p><p>Gupta sculpture emphasised balanced idealism; Chola bronzes used lost-wax casting and dynamic devotional icons. Iconography identifies attributes and narratives, but regional workshops vary. Temple sculpture integrates architecture, ritual, cosmology and social imagery.</p>`},
{id:'painting',title:'Painting traditions',html:`<p>Prehistoric rock art records long occupation. Ajanta murals use narrative, modelling and expressive line in Buddhist contexts. Manuscript traditions include Pala and Jain schools. Mughal ateliers developed portrait, naturalism and chronicle illustration; Deccani painting favoured rich colour and fantasy; Rajput/Pahari schools interpreted court, devotion, season and poetry.</p><p>Company painting adapted Indian skill to colonial patrons; nationalist and modern artists debated academic realism, indigenous forms and global modernism.</p>`},
{id:'literature',title:'Language and literature',html:`<p>Vedic, epic, Buddhist, Jain, Sangam, classical Sanskrit/Prakrit/Pali, Persian, Arabic and vernacular literatures preserve philosophy, polity, devotion and social memory. Bhakti and Sufi expression helped regional languages gain public reach. Court patronage and oral performance coexisted with manuscript cultures.</p><p>Texts are sources with genre: eulogy, law book, epic and devotional lyric cannot be read as neutral census reports.</p>`},
{id:'performance',title:'Music, dance and theatre',html:`<p>Indian classical music developed raga (melodic framework) and tala (rhythm), with Hindustani and Carnatic traditions sharing roots but diverging historically in repertoire and performance. Dhrupad, khayal and devotional forms are distinct; instruments classify by string, wind, membrane and solid percussion.</p><p>Classical dance forms combine codified gesture, rhythm, expression and regional history; folk and tribal forms are living community traditions, not “less developed” classical forms. Theatre ranges from Sanskrit theory to regional ritual and modern political performance.</p>`},
{id:'religion',title:'Religious ideas and cultural exchange',html:`<p>Vedic, Buddhist, Jain, Hindu devotional, Sikh, Islamic, Christian and other traditions shaped institutions and arts through debate and interaction. Temple, monastery, mosque, dargah, church and gurudwara were ritual spaces and often social-economic nodes.</p><p>Indian culture is marked by continuity, reinterpretation and regional plurality. Avoid claims of unchanged purity or seamless synthesis; ask which groups, period and evidence.</p><div class="exam-box"><b>Culture answer:</b> feature → function → patron/community → regional example → continuity/change → present conservation issue.</div><p class="source-note">Update UNESCO/heritage status only from official ASI, Culture Ministry and UNESCO sources.</p>`}
],recall:['Apply the eight-field culture card.','Compare Nagara and Dravida without absolutes.','Gandhara versus Mathura?','How does genre affect texts?','Why distinguish classical, folk and tribal without hierarchy?']};

BOOKS['05']={total:13,title:'British Conquest & Colonial State',kicker:'Book 05 · Company to Crown',dek:'Eighteenth-century politics, Company expansion, colonial administration, law and early resistance.',prev:'04-indian-art-and-culture.html',next:'06-colonial-economy-and-society.html',sections:[
{id:'context',title:'Eighteenth-century context',html:`<p>Mughal decentralisation produced successor states and regional powers while commerce and banking remained active. European companies competed within Indian political systems before the English Company gained decisive fiscal-military power. British conquest was contingent, not inevitable.</p>`},
{id:'bengal',title:'Bengal and the Company state',html:`<p>Plassey (1757) followed court politics, Company privilege and conspiracy; Buxar (1764) defeated combined regional forces and strengthened Company leverage. The 1765 Diwani gave revenue rights in Bengal, Bihar and Orissa, allowing Indian revenue to finance trade and war.</p><p>Dual government separated nominal authority from fiscal control and weakened accountability. Revenue extraction, private trade and famine exposed Company rule, prompting parliamentary regulation.</p>`},
{id:'expansion',title:'Expansion across India',html:`<p>Anglo-Mysore wars confronted a state modernising army, revenue and trade under Haidar Ali and Tipu Sultan. Anglo-Maratha wars exploited confederacy divisions and treaty politics. Anglo-Sikh wars followed changing Punjab power after Ranjit Singh. Subsidiary alliances stationed Company forces and constrained diplomacy; Doctrine of Lapse annexed states lacking a recognised natural heir.</p><div class="chain">Revenue base → disciplined army and credit → war/treaty → territorial revenue → larger military-fiscal capacity.</div>`},
{id:'administration',title:'Administrative and constitutional growth',html:`<p>Regulating Act 1773 began parliamentary control; Pitt’s India Act 1784 created dual oversight; Charter Acts changed trade monopoly and administration; 1858 transferred rule to the Crown. Cornwallis reforms reshaped civil service, police and courts while institutionalising racial exclusion.</p><p>Colonial law claimed uniformity but preserved personal-law categories and special powers. Codification, census and surveys made society “legible” while fixing fluid identities.</p>`},
{id:'army',title:'Army, communication and knowledge',html:`<p>The Company recruited Indian soldiers under European command, exploiting regional labour markets and political divisions. Military drill, finance and supply were decisive. Roads, post, telegraph and later railways aided control while creating wider social-economic effects.</p><p>Maps, surveys, gazetteers, ethnography and censuses were tools of knowledge and rule. Their categories are valuable sources but not neutral descriptions.</p>`},
{id:'resistance',title:'Early resistance and tribal-peasant uprisings',html:`<p>Sanyasi-Fakir resistance, Polygar struggles, Paika rebellion, Santhal Hul, Kol uprising and many local movements arose from dispossession, revenue pressure, outsider penetration, forest controls and defence of authority/community. Their aims were diverse and not simply early nationalism.</p><p>Understanding local ecology, leadership, social coalition and colonial response avoids turning every uprising into the same story.</p>`},
{id:'assessment',title:'Nature of the colonial state',html:`<p>The colonial state sought revenue, order and imperial advantage; it also built law, infrastructure and institutions shaped by those priorities. Liberal claims coexisted with racial hierarchy and coercion. Indian intermediaries were essential, making rule both foreign-dominated and locally embedded.</p><div class="exam-box"><b>Conquest answer:</b> Indian political context + Company military-fiscal advantages + diplomacy/intermediaries + contingency + consequences.</div><p class="source-note">Map battles, annexations, presidencies, resistance zones and communication expansion.</p>`}
],recall:['Why was conquest not inevitable?','Plassey versus Buxar significance?','Explain the military-fiscal cycle.','How did knowledge aid rule?','Why were early uprisings not one ideology?']};

BOOKS['06']={total:13,title:'Colonial Economy & Society',kicker:'Book 06 · Extraction and transformation',dek:'Land revenue, commercialisation, industry, infrastructure, famines, forests, peasants and labour.',prev:'05-british-conquest-and-colonial-state.html',next:'07-reform-education-and-press.html',sections:[
{id:'revenue',title:'Land-revenue systems',html:`<p>Permanent Settlement fixed state demand through zamindars in Bengal but did not fix cultivators’ rents; Ryotwari dealt formally with individual cultivators in much of south/west; Mahalwari assessed villages/estates in parts of north. Actual practice varied and demand could be heavy under all.</p><p>Revenue pressure, uncertain rights, debt and intermediaries reshaped rural class relations. No system simply created modern private property uniformly.</p>`},
{id:'commercial',title:'Commercialisation and agrarian change',html:`<p>Cash crops expanded through global demand, advances, contracts, coercion and transport. Indigo, cotton, opium, jute, tea and others linked cultivators to volatile markets. Commercialisation could create income for some while increasing food, debt and price risks.</p><p>Deccan riots, Indigo revolt and peasant movements combined economic grievances with local organisation and legal/political repertoires.</p>`},
{id:'industry',title:'Deindustrialisation and modern industry',html:`<p>Indian handicrafts faced Company procurement practices, tariff asymmetry, machine imports, changing courts and demand, though regional crafts adapted unevenly. “Deindustrialisation” varied by sector and period.</p><p>Modern cotton, jute, coal, iron-steel and plantation industries grew under Indian and European capital. Managing agencies, colonial finance, infrastructure and labour migration shaped them. Industrial growth did not erase structural dependence.</p>`},
{id:'drain',title:'Drain of wealth and colonial trade',html:`<p>Nationalists argued that “home charges,” profits, pensions, debt payments and unrequited export surplus transferred resources without equivalent return. Dadabhai Naoroji made drain theory a systematic critique linking poverty to foreign rule.</p><p>India exported primary goods and imported manufactures within imperial networks. Exchange, shipping, finance and fiscal policy served metropolitan priorities while also generating Indian commercial groups.</p>`},
{id:'rail',title:'Railways, irrigation and infrastructure',html:`<p>Railways integrated markets, enabled troop movement and exports, encouraged some industry and mobility, and were built under guarantee arrangements that socialised risk. Benefits were real but shaped by colonial routing, tariffs and finance.</p><p>Canals raised output in some zones while creating waterlogging, salinity and unequal access. Infrastructure must be evaluated by design, beneficiaries, financing and opportunity cost.</p>`},
{id:'famine',title:'Famines, forests and ecology',html:`<p>Drought became famine through crop failure, prices, lost entitlements, revenue policy, export, weak relief and ideology. Late nineteenth-century famines exposed limits of laissez-faire response. Famine codes developed but implementation varied.</p><p>Forest laws asserted state control, reserved timber and restricted shifting cultivation, grazing and collection. “Scientific forestry” served commercial/state needs and transformed community ecology, provoking resistance.</p>`},
{id:'labour',title:'Labour, migration and social change',html:`<p>Plantations, mines, mills and overseas indenture drew workers through recruiters, debt and limited alternatives. Contracts and penal rules constrained freedom. Cities developed new classes, associations and segregation.</p><div class="concept-box"><b>Colonial modernity was uneven:</b> markets, law and infrastructure expanded alongside extraction, racial power and new inequality.</div><p class="source-note">Link economic themes to regions: revenue zones, cash crops, ports, railways, mines, factories and famine areas.</p>`}
],recall:['Compare three land systems without oversimplifying.','Commercialisation: opportunity and coercion?','Explain drain theory.','Evaluate railways from multiple perspectives.','Why does drought not automatically equal famine?']};

BOOKS['07']={total:13,title:'Reform, Education & Press',kicker:'Book 07 · Society debates itself',dek:'Religious and social reform, caste, gender, education, press and the making of a public sphere.',prev:'06-colonial-economy-and-society.html',next:'08-freedom-struggle-1857-1919.html',sections:[
{id:'context',title:'Conditions of reform',html:`<p>Colonial power, print, missionary critique, Orientalist knowledge, new education and indigenous debates changed the public sphere. Reformers reinterpreted tradition rather than simply choosing “West” or “India.” Region, caste, class, language and gender produced multiple reform agendas.</p>`},
{id:'religious',title:'Religious-social organisations',html:`<p>Rammohan Roy and Brahmo traditions opposed sati and idolatry and promoted monotheism, reason and women’s rights. Arya Samaj invoked Vedic authority, education and shuddhi. Prarthana Samaj pursued social/religious reform in western India. Ramakrishna–Vivekananda emphasised spiritual universalism and service.</p><p>Aligarh movement under Sir Syed promoted modern education among Muslims; Deoband pursued Islamic learning and reform with different politics. Singh Sabha reshaped Sikh identity. Theosophy connected spiritual revival and education. Each movement had internal changes and limits.</p>`},
{id:'caste',title:'Caste critique and lower-caste movements',html:`<p>Jyotirao and Savitribai Phule attacked Brahmanical domination and expanded education; Satyashodhak Samaj organised non-Brahman assertion. Narayana Guru challenged hierarchy in Kerala; Periyar’s Self-Respect movement attacked caste, patriarchy and religious authority. Ambedkar linked caste annihilation to rights, representation, education and political power.</p><p>Reform “for” oppressed groups differs from autonomous movements “by” them. Examine voice, organisation and structural demand.</p>`},
{id:'women',title:'Women and gender reform',html:`<p>Campaigns addressed sati, widow remarriage, child marriage, education, age of consent, property and purdah. Ishwar Chandra Vidyasagar, Pandita Ramabai, Begums of Bhopal and many women educators/writers shaped debate. Colonial legislation interacted with community politics.</p><p>Women were not only beneficiaries: they wrote, taught, organised and later joined nationalism. Reform sometimes created an ideal “new woman” constrained by domestic respectability.</p>`},
{id:'education',title:'Education and intellectual change',html:`<p>Orientalist–Anglicist debate concerned language, curriculum and purpose. Macaulay’s Minute and later policy expanded English education selectively; Wood’s Despatch proposed a wider system; universities emerged in 1857. Missionary, government and indigenous institutions coexisted.</p><p>Education produced clerks and professionals, public debate and nationalism, but access remained unequal. National education, women’s schools and institutions such as Aligarh, BHU and others reflected competing visions.</p>`},
{id:'press',title:'Press, literature and public associations',html:`<p>Vernacular and English newspapers spread ideas, connected regions and criticised policy. Licensing and the Vernacular Press Act sought control; editors used legal and rhetorical strategies. Novels, pamphlets, theatre and satire imagined community and debated society.</p><p>Associations trained petition, meeting, fundraising and representation, forming infrastructure later used by nationalism.</p>`},
{id:'assessment',title:'Achievements and limitations',html:`<p>Reform widened critique, education and legal change but was often urban, elite or regionally narrow. It could reproduce paternalism, communal boundary-making or caste limits. Yet autonomous lower-caste, women’s and community movements expanded the agenda.</p><div class="exam-box"><b>Reformer answer:</b> context → ideas → organisation/method → social base → achievements → limits → legacy.</div><p class="source-note">Compare movements by region, social base, scripture/reason, education, gender and relation to colonial rule.</p>`}
],recall:['Why is “West versus tradition” inadequate?','Compare Brahmo, Arya and Aligarh.','Reform for versus movement by?','How did women act as agents?','Apply the seven-part reformer frame.']};
